### PR TITLE
Angstrom v2020.06 dunfell

### PR DESCRIPTION
**Pull request by marioecht**
Maintenance of systemd recipes.

### CODE REVIEW

**Comment by koenkooi** [comment]
Sysvinit support was disabled on purpose, is there a way to install legacy.conf without turning on sysvinit support? It's been a few years, but I think it was disabled because most initscripts in OE have broken LSB headers, which systemd actually parses and uses.

**Comment by koenkooi** [comment]
The removal of the old recipes is good to go in, though.

**Comment by marioecht** [comment]
Until systemd version 243 there was no configuration possibility for sysvinit. [https://git.openembedded.org/openembedded-core/tree/meta/recipes-core/systemd/systemd_243.2.bb?h=zeus#n64](https://git.openembedded.org/openembedded-core/tree/meta/recipes-core/systemd/systemd_243.2.bb?h=zeus#n64)

At least with my builds systemd sysvinit was always active.

Starting with systemd version 244 sysvinit can be configured separately. 
[https://git.openembedded.org/openembedded-core/tree/meta/recipes-core/systemd/systemd_244.3.bb?h=dunfell#n59](https://git.openembedded.org/openembedded-core/tree/meta/recipes-core/systemd/systemd_244.3.bb?h=dunfell#n59)
In OE-core recipe the option is only now available.

I assume that systemd_%.bbappend comes from an ealier version of systemd, the sysvinit option is not set.

**Comment by koenkooi** [comment]
Ah, so this is separate from not having 'sysvinit' in DISTRO_FEATURES :/

https://git.openembedded.org/openembedded-core/tree/meta/recipes-core/systemd/systemd_243.2.bb?h=zeus#n237

**Comment by koenkooi** [comment]
Merged, many, many thanks for looking into this!

**Pull request merged**
